### ISSUE TITLE
error:  Error: Error exporting file

### ISSUE THREAD

**Issue by dunstan** [tonistiigi/audiosprite#74]
I have a question about an error, and two small additional questions:

1. I tried running this for the first time and got the error shown below. Could anyone explain it to me, please? I have FFmpeg installed.
2. I specified a 2 second silence gap, but it says "Silence gap added duration=3". Why the extra second?
3. Is there a way to add silence to the start of the track, too?

Thanks very much.

------

$ audiosprite -s 2 -o combo1 'AARON GERVAIS (LOUIS CK AM SPINRADE).mp3' 'ALICIA WALTER (REAL TALK).mp3 BIRTHMARK' '(LOVE POWER).mp3'

info: Silence gap added duration=3
info:  0=AARON GERVAIS (LOUIS CK AM SPINRADE).mp3
info: File added OK file=/var/folders/qq/wjmnhkns4vjb1r77hqv2f1pr0000gn/T/audiosprite.14227197977886363, duration=155.37632653061223
info: Silence gap added duration=1.623673469387768

error:  Error: Error exporting file
    at /usr/local/lib/node_modules/audiosprite/audiosprite.js:312:27
    at /usr/local/lib/node_modules/audiosprite/node_modules/async/lib/async.js:148:21
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/audiosprite/audiosprite.js:190:18)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

**Comment by SargoDarya** [comment]
I have to admit that the error isn't really descriptive. I won't be able to fix that today but I will take a look into this later tomorrow.

**Comment by SargoDarya** [comment]
Sorry, haven't had the time yet to look into it. Can you maybe prepare a zip file containing your setup so I have an exact thing to test this easier?

**Comment by etall** [comment]
the same error 

/usr/local/lib/node_modules/audiosprite/audiosprite.js:312:27

mac 10.13.5
ffmpeg version 4.0.1
node v10.8.0

**Comment by SargoDarya** [comment]
@etall @metalim Can you guys provide a sample zip with the setup you used so I can investigate that further?

**Comment by maksmaers** [comment]
@SargoDarya I had the same issue, after debugging I found result for **ffmpeg** command
 ffmpeg -y -ar 44100 -ac 1 -f s16le -i /tmp/audiosprite.9684745136330044 -acodec libvorbis -f ogg -ab 128k output.ogg
and I got console error 
**/tmp/audiosprite.9684745136330044: No such file or directory**
if I create this file it is ok

Debug log

> debug: Parsed arguments _=[src/assets/sounds/source/*.mp3], l=debug, log=debug, output=output, o=output, path=, u=, export=ogg,m4a,mp3,ac3, e=ogg,m4a,mp3,ac3, format=jukebox, f=jukebox, autoplay=null, a=null, loop=null, silence=0, s=0, gap=1, g=1, minlength=0, m=0, bitrate=128, b=128, vbr=-1, v=-1, vbr:vorbis=-1, q=-1, samplerate=44100, r=44100, channels=1, c=1, rawparts=, p=, ignorerounding=0, i=0, $0=/usr/bin/node ./node_modules/.bin/audiosprite
> /tmp/audiosprite.9760795878685962
> debug: Created temporary file file=/tmp/audiosprite.9760795878685962
> debug: Spawn cmd=ffmpeg -version
> ffmpeg -version
> info: 
> debug: Start export format=ogg
> debug: Spawn cmd=ffmpeg -y -ar 44100 -ac 1 -f s16le -i /tmp/audiosprite.9760795878685962 -acodec libvorbis -f ogg -ab 128k output.ogg
> ffmpeg -y -ar 44100 -ac 1 -f s16le -i /tmp/audiosprite.9760795878685962 -acodec libvorbis -f ogg -ab 128k output.ogg
> null
> error:  Error: Error exporting file

**Comment by maksmaers** [comment]
```
const tempFile = mktemp('audiosprite');
  
  fs.writeFile(tempFile, '', (err) => {
    if (err) throw err;
    opts.logger.debug("The file was succesfully saved!");
  })
```

**Comment by danclong** [comment]
If you're on Mac, you **have** to install the dependencies exactly as the documentation states:

`brew install ffmpeg --with-theora --with-libvorbis`

I had installed `ffmpeg` previously with Homebrew, but not with the options above. Re-installed as above and it works fine now.

**Comment by SargoDarya** [comment]
Even if that works we probably should add better error reporting. Error exporting file just doesn't cut it.

**Comment by mnovbaalen** [comment]
I had the same error: Error exporting file. 
Running the ffmpeg command manually was working without problems.

It seems to be that audiosprite does not work with ffmpeg 4.x:

At first I installed ffmpeg with snap on Ubuntu 18 LTS. (This is ffmpeg version 4.x.)
When de-installing this version of ffmpeg and installing ffmpeg with the command
```bash
sudo apt install ffmpeg
``` 
ffmpeg 3.x is installed, and the problem is solved!

see also: https://linuxize.com/post/how-to-install-ffmpeg-on-ubuntu-18-04/

**Comment by madclaws** [comment]
> I had the same error: Error exporting file.
> Running the ffmpeg command manually was working without problems.
> 
> It seems to be that audiosprite does not work with ffmpeg 4.x:
> 
> At first I installed ffmpeg with snap on Ubuntu 18 LTS. (This is ffmpeg version 4.x.)
> When de-installing this version of ffmpeg and installing ffmpeg with the command
> 
> ```shell
> sudo apt install ffmpeg
> ```
> 
> ffmpeg 3.x is installed, and the problem is solved!
> 
> see also: https://linuxize.com/post/how-to-install-ffmpeg-on-ubuntu-18-04/

This worked for me

**Comment by ruthgrace** [comment]
on mac osx. upgraded from ffmpeg version 3.4.2 to 4.4 using brew, and was able to get over this error. maybe audiosprite has been updated to only work with ffmpeg 4 now?

**Comment by RedRoosterMobile** [comment]
I circumvented the bug by using `-e mp3` option..

**Comment by fluffy-critter** [comment]
I'm having this problem with ffmpeg 8.1.2 (homebrew) on macOS 26.5.2. The error I'm getting is just:

```
error:  Error: Error exporting file
    at /opt/homebrew/lib/node_modules/audiosprite/audiosprite.js:321:27
    at /opt/homebrew/lib/node_modules/audiosprite/node_modules/async/lib/async.js:148:21
    at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/audiosprite/audiosprite.js:199:18)
    at ChildProcess.emit (node:events:509:20)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```

**Comment by fluffy-critter** [comment]
For me the fix was to switch to `audiosprite-ffmpeg` which seems to work correctly.
